version: "3.7"

services:
  replicated:
    image: pythonincontainers/big-mem:v1
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 300M
    ports:
      - target: 5000
        published: 5001
        mode: ingress
